# This builds an image that contains the resources needed by Dockerfile
#
FROM scratch

# Copy resources downloaded via download_deps.py
COPY chromedriver-linux64-121-0-6167-85 chrome-linux64-121-0-6167-85 cl100k_base.tiktoken tika-server-standard-3.0.0.jar tika-server-standard-3.0.0.jar.md5  /

COPY nltk_data /nltk_data

COPY huggingface.co /huggingface.co
